name: KingdomsOfArden-Invasion
version: 1.0
description: Mob Invasions to Overworld
author: Andrew2060
website: http://www.kingdomsofarden.net/
main: net.kingdomsofarden.andrew2060.invasion.InvasionPlugin
depend: [Heroes, KingdomsOfArden-PluginAPI]